name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1. Configurar Java (necesario para las herramientas de Flutter)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # 2. Instalar y configurar Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # 3. Descargar dependencias y compilar el proyecto Flutter Web
      - name: Build Flutter Web
        run: |
          cd minesweeper_ui
          flutter pub get
          flutter build web --base-href "/Buscaminas/"

      # 4. Configurar la estructura de GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 5. Subir la carpeta compilada (build/web) como artefacto
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './minesweeper_ui/build/web'

      # 6. Desplegar en GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
